server:
  port: 8080
  servlet:
    context path: /test
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test-connect"
    username: root
    password: dtvn2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true